{{- if and .Values.managementcenter.enabled (and .Values.managementcenter.yaml (not .Values.managementcenter.existingConfigMap)) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "managementcenter.fullname" . }}-configuration
  labels:
    app.kubernetes.io/name: {{ template "hazelcast-jet.name" . }}
    helm.sh/chart: {{ template "hazelcast-jet.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
data:
  hazelcast-client.yaml: |-
{{ toYaml .Values.managementcenter.yaml | indent 4 }}
{{- end -}}
